service: tutorial
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2

functions:
  api:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: post

      - httpApi:
          path: /hello
          method: get
