service: aws-node-sqs-worker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  
functions:
  producer_consumer:
    handler: handler.hello
    events:
      - httpApi:	
          method: post
          path: /hello

plugins:
  - serverless-lift